### PR TITLE
Fix: Invalidate ReturnData::sllh on backwards integration failure

### LINKED ISSUE #1325: ReturnData::sllh not set to NaN upon backwards integration failures
Upon backwards integration failures, `ReturnData::sllh` should be set to NaN instead of being left in an undefined state. This seems to be broken.

Invalidating sllh seems to rely on `BackwardProblem*` being `nullptr` in `ReturnData::processSimulationObjects`. Not sure in which situations that would be the case, but not when running into `IntegrationFailureB`.

### PR DESCRIPTION
**Pull request by dweindl**
Closes #1325

### CODE REVIEW

File: src/amici.cpp [hunk 1]
```diff
@@ -187,8 +191,10 @@ AmiciApplication::runAmiciSimulation(Solver& solver,
                  ex.getBacktrace());
     }
 
-    rdata->processSimulationObjects(preeq.get(), fwd.get(), bwd.get(),
-                                    posteq.get(), model, solver, edata);
+    rdata->processSimulationObjects(
+        preeq.get(), fwd.get(),
+        bwd_success?bwd.get():nullptr,
```
Comment (FFroehlich) [inline src/amici.cpp:196]:
```suggestion
        bwd_success ? bwd.get() : nullptr,
```

File: src/amici.cpp [hunk 2]
```diff
@@ -155,6 +158,7 @@ AmiciApplication::runAmiciSimulation(Solver& solver,
                 preeq->workSteadyStateBackwardProblem(&solver, &model,
                                                       bwd.get());
             }
+            bwd_success = true;
```
Comment (FFroehlich) [inline src/amici.cpp:161]: that's `posteq` and not `bwd` though

**Review by FFroehlich — APPROVED** [review]

File: src/amici.cpp (hunk 2 above)
Comment (dweindl) [reply src/amici.cpp]: Changed.
