### PR TITLE
Steady state tolerance factor

### LINKED ISSUE #1755: Default steady-state-by-simulation tolerances should be higher
Can include a MWE if desired, not yet prepared.

Using the Blasi problem [1] with a parameter vector supplied by @plakrisenko .

At default tolerances, using simulation to find the steady state, `wrms_` [2] seems to fluctuate a bit and never gets below the threshold of `1`. Printed here are the `wrms_` values at [2] that were printed immediately before the error.
```
152.175
26.3248
152.175
26.3248
152.175
99.5254
152.175
99.5254
152.175
99.5254
152.175
26.3249
26.3249
152.175
26.3249
26.3249
26.3249
152.175
26.3249
26.3248
26.3247
152.175
26.3248
26.3249
152.175
26.3248
26.3249
26.3249
26.3248
26.3248
26.3248
26.3248
152.175
26.3249
152.175
26.3248
152.175
99.5253

[Warning] AMICI:CVODES:CVode:OTHER: AMICI ERROR: in module CVODES in function CVode : At t = 5.01122e+199, the right-hand side routine failed in an unrecoverable manner. 
[Warning] AMICI:equilibration: AMICI equilibration failed: AMICI failed to integrate the forward problem

[Warning] AMICI:simulation: AMICI simulation failed:
Steady state computation failed. First run of Newton solver failed: No convergence was achieved. Simulation to steady state failed. Second run of Newton solver failed: No convergence was achieved.
Error occurred in:
0       0x7fe37c02f3f6 amici::AmiException::AmiException() + 38
1       0x7fe37c02f4bb amici::AmiException::AmiException(char const*, ...) + 123
2       0x7fe37bf862e0 /home/dilan/Documents/future_annex/steady_state_paper/20220331_debug_conservation_laws/before/packages/AMICI/python/sdist/amici/_amici.cpython-38-x86_64-linux-gnu.so(+0xab2e0) [0x7fe37bf862e0]
3       0x7fe37c0862c9 /home/dilan/Documents/future_annex/steady_state_paper/20220331_debug_conservation_laws/before/packages/AMICI/python
```
Printed here is the same thing, but with the steady state tolerances set to two orders of magnitude above default simulation tolerances. The `wrms_` values decrease monotonically (unlike above) to a value less than the threshold `1`,.
```
1291.25
1049.53
853.222
693.769
564.23
458.968
373.41
303.853
247.294
201.298
163.883
133.443
108.672
78.884
57.2981
41.6431
30.2707
22.0027
15.9956
9.63246
5.86245
3.6014
2.20007
1.32276
# Success
0.794022
```

A possible solution would be to change steady-state-by-simulation tolerances to be some factor of simulation tolerances, e.g.:
```cpp
solver->setSteadyStateToleranceFactor(1e+2)

// Replace everywhere `solver->getAbsoluteToleranceSteadyState()` with simulation tolerance increased by the factor:
solver->getAbsoluteTolerance() * solver->getSteadyStateToleranceFactor()

// Replace everywhere `solver->getRelativeToleranceSteadyState()` with simulation tolerance increased by the factor:
solver->getRelativeTolerance() * solver->getSteadyStateToleranceFactor()
```

[1] https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/tree/master/Benchmark-Models/Blasi_CellSystems2016
[2] https://github.com/AMICI-dev/AMICI/blob/master/src/steadystateproblem.cpp#L456=

### PR DESCRIPTION
**Pull request by dilpath**
Closes #1755, thanks for the feedback there.

`operator==` is left unchanged as it (practically) already covers the new settings [1]

An alternative to these new settings would be to simply add a fixed multiplier e.g. `* 100.0` at [2]

I didn't test extensively, but a factor of `1e1` was sufficient for the single problem I looked at. The default factors in this PR are set to `1e2`.

[1] https://github.com/AMICI-dev/AMICI/blob/3d4975cd7fbffd9be588bc8b8f1e925590b3931f/src/solver.cpp#L500-L507=
[2] https://github.com/AMICI-dev/AMICI/blob/3d4975cd7fbffd9be588bc8b8f1e925590b3931f/src/solver.cpp#L796=

### CODE REVIEW

File: include/amici/solver.h [hunk 1]
```diff
@@ -384,6 +384,24 @@ class Solver {
      */
     void setAbsoluteToleranceQuadratures(double atol);
 
+    /**
+     * @brief returns the steady state simulation tolerance factor.
+     * Steady state simulation tolerances are the product of the simulation
```
Comment (dweindl) [inline include/amici/solver.h:389]:
```suggestion
     * @brief returns the steady state simulation tolerance factor.
     *
     * Steady state simulation tolerances are the product of the simulation
```
Otherwise the full description is considered part of `brief`.

File: include/amici/solver.h [hunk 2]
```diff
@@ -384,6 +384,24 @@ class Solver {
...
+     * tolerances and this factor, unless manually set with
+     * `set(Absolute/Relative)ToleranceSteadyState()`.
+     * @return steady state simulation tolerance factor
+     */
+    double getSteadyStateToleranceFactor() const;
+
+    /**
+     * @brief set the steady state simulation tolerance factor.
+     * Steady state simulation tolerances are the product of the simulation
```
Comment (dweindl) [inline include/amici/solver.h:398]:
```suggestion
     * @brief set the steady state simulation tolerance factor.
     *
     * Steady state simulation tolerances are the product of the simulation
```

File: include/amici/solver.h [hunk 3]
```diff
@@ -408,6 +426,24 @@ class Solver {
      */
     void setAbsoluteToleranceSteadyState(double atol);
 
+    /**
+     * @brief returns the steady state sensitivity simulation tolerance factor.
+     * Steady state sensitivity simulation tolerances are the product of the
```
Comment (dweindl) [inline include/amici/solver.h:431]:
```suggestion
     * @brief returns the steady state sensitivity simulation tolerance factor.
     *
     * Steady state sensitivity simulation tolerances are the product of the
```

File: include/amici/solver.h [hunk 4]
```diff
@@ -408,6 +426,24 @@ class Solver {
...
+     * sensitivity simulation tolerances and this factor, unless manually set
+     * with `set(Absolute/Relative)ToleranceSteadyStateSensi()`.
+     * @return steady state simulation tolerance factor
+     */
+    double getSteadyStateSensiToleranceFactor() const;
+
+    /**
+     * @brief set the steady state sensitivity simulation tolerance factor.
+     * Steady state sensitivity simulation tolerances are the product of the
```
Comment (dweindl) [inline include/amici/solver.h:440]:
```suggestion
     * @brief set the steady state sensitivity simulation tolerance factor.
     *
     * Steady state sensitivity simulation tolerances are the product of the
```

File: src/hdf5.cpp [hunk 5]
```diff
@@ -794,6 +793,11 @@ void readSolverSettingsFromHDF5(H5::H5File const& file, Solver &solver,
                     getDoubleScalarAttribute(file, datasetPath, "quad_rtol"));
     }
 
+    if(attributeExists(file, datasetPath, "ss_tol_factor")) {
```
Comment (dweindl) [inline src/hdf5.cpp:796]: Could you please also update `writeSolverSettingsToHDF5` (same file) accordingly?

**Review by dweindl — APPROVED** [review]
Looks good to me.

File: src/hdf5.cpp (hunk 5 above)
Comment (dilpath) [reply src/hdf5.cpp:804]: :see_no_evil:

**Comment by dweindl** [comment]
Remaining PEtab test failure will be fixed by #1753
