### PR TITLE
fix setting of maximum number of steps, fixes #726

### LINKED ISSUE #726: solver.setMaxSteps() is not working correctly
I managed to simulate a model past (as indicated by `rdata['numsteps'])` the specified number of maximal steps specified by `solver.setMaxSteps()` . Seems to be dependent on specifying simulation timepoints prior to to the timepoint where the maximum number of steps is reached. Current hypothesis is that only number of steps between timepoints in penalized and not total.

### PR DESCRIPTION
**Pull request by FFroehlich**

### CODE REVIEW

File: include/amici/solver.h [hunk 1]
```diff
@@ -1130,6 +1130,7 @@ class Solver {
      * problem
      *
      * @param mxsteps number of steps
+     * @note in contrast to the SUNDIALS method, this sets the overall maximu, not the maximum between output times.
```
Comment (dweindl) [inline include/amici/solver.h:1133]:
```suggestion
     * @note in contrast to the SUNDIALS method, this sets the overall maximum, not the maximum between output times.
```

**Review by dweindl — APPROVED** [review]
Looks good. Want to address `maxstepsB_` here as well?

File: src/solver.cpp [hunk 2]
```diff
@@ -36,10 +36,20 @@ Solver::Solver(const Solver &other)
       maxstepsB_(other.maxstepsB_), sensi_(other.sensi_)
 {}
 
+void Solver::apply_max_num_steps() const {
+    // set remaining steps, setMaxNumSteps only applies to a single call of solve
+    long int cursteps;
+    getNumSteps(solver_memory_.get(), &cursteps);
+    setMaxNumSteps(maxsteps_-cursteps);
```
Comment (dweindl) [inline src/solver.cpp]: Wait, we need to be careful here: in the (probably rare) case, where the solver just reaches `tout` with `maxsteps` steps, this passes `0` to SUNDIALS, which is interpreted as default value (500). In the following step, this will get negative which is interpreted as "no limit".

**Comment by FFroehlich** [comment]
> Looks good. Want to address `maxstepsB_` here as well?

👍  done.

File: src/solver.cpp (hunk 2 above)
Comment (dweindl) [reply src/solver.cpp]: Corner-case, but that would be fun to debug :D

Comment (FFroehlich) [reply src/solver.cpp]: good catch!

File: src/solver.cpp [hunk 3]
```diff
@@ -36,10 +36,39 @@ Solver::Solver(const Solver &other)
       maxstepsB_(other.maxstepsB_), sensi_(other.sensi_)
 {}
 
+void Solver::apply_max_num_steps() const {
+    // set remaining steps, setMaxNumSteps only applies to a single call of solve
+    long int cursteps;
+    getNumSteps(solver_memory_.get(), &cursteps);
+    if (maxsteps_ <= cursteps)
+        throw AmiException("Reached maximum number of steps %i before reaching "
+                           "tout at t=%d.", maxsteps_, t_);
```
Comment (dweindl) [inline src/solver.cpp:45]:
```suggestion
                           "tout at t=%g.", maxsteps_, t_);
```

File: src/solver.cpp [hunk 4]
```diff
@@ -36,10 +36,39 @@ Solver::Solver(const Solver &other)
...
+void Solver::apply_max_num_steps_B() const {
+    // set remaining steps, setMaxNumSteps only applies to a single call of solve
+    long int curstepsB;
+    auto maxstepsB = (maxstepsB_ == 0) ? maxsteps_ * 100 : maxstepsB_;
+    for (int i_mem_b = 0; i_mem_b < (int)solver_memory_B_.size(); ++i_mem_b) {
+        if (solver_memory_B_.at(i_mem_b)) {
+            getNumSteps(solver_memory_B_.at(i_mem_b).get(), &curstepsB);
+            if (maxstepsB <= curstepsB)
+                throw AmiException("Reached maximum number of steps %i before "
+                                   "reaching tout at t=%d     in backward "
```
Comment (dweindl) [inline src/solver.cpp:58]:
```suggestion
                                   "reaching tout at t=%g in backward "
```

File: src/solver.cpp [hunk 5]
```diff
@@ -36,10 +36,39 @@ Solver::Solver(const Solver &other)
...
+
+void Solver::apply_max_num_steps_B() const {
+    // set remaining steps, setMaxNumSteps only applies to a single call of solve
+    long int curstepsB;
+    auto maxstepsB = (maxstepsB_ == 0) ? maxsteps_ * 100 : maxstepsB_;
+    for (int i_mem_b = 0; i_mem_b < (int)solver_memory_B_.size(); ++i_mem_b) {
+        if (solver_memory_B_.at(i_mem_b)) {
+            getNumSteps(solver_memory_B_.at(i_mem_b).get(), &curstepsB);
+            if (maxstepsB <= curstepsB)
+                throw AmiException("Reached maximum number of steps %i before "
```
Comment (dweindl) [inline src/solver.cpp:57]:
```suggestion
                throw AmiException("Reached maximum number of steps %ld before "
```

File: src/solver.cpp [hunk 6]
```diff
@@ -36,10 +36,39 @@ Solver::Solver(const Solver &other)
       maxstepsB_(other.maxstepsB_), sensi_(other.sensi_)
 {}
 
+void Solver::apply_max_num_steps() const {
+    // set remaining steps, setMaxNumSteps only applies to a single call of solve
+    long int cursteps;
+    getNumSteps(solver_memory_.get(), &cursteps);
+    if (maxsteps_ <= cursteps)
+        throw AmiException("Reached maximum number of steps %i before reaching "
```
Comment (dweindl) [inline src/solver.cpp:44]:
```suggestion
        throw AmiException("Reached maximum number of steps %ld before reaching "
```

**Review by dweindl — APPROVED** [review]
