### PR TITLE
Harmonize Fixed parameter Names

### LINKED ISSUE #975: Harmonize Constant/FixedParameter/ConstantParameter
happy to discuss what they should be called.

condition
feature
constant

### PR DESCRIPTION
**Pull request by FFroehlich**
fixes #975

### CODE REVIEW

**Comment by dweindl** [comment]
[Notebook tests Ubuntu (3.11)](https://github.com/AMICI-dev/AMICI/actions/runs/19356699226/job/55379253028?pr=3027#logs) fails due to the unfortunate pypesto dependency. Will update pypesto after this is merged.

We may want to consider moving that spline-parameter-estimation example to pypesto and just referencing it here.

File: include/amici/model.h [hunk 1]
```diff
@@ -565,18 +567,18 @@ class Model : public AbstractModel, public ModelDimensions {
     virtual std::string get_name() const;
 
     /**
-     * @brief Report whether the model has parameter names set.
+     * @brief Report whether the model has free parameter names set.
      *
-     * @return Boolean indicating whether parameter names were set. Also returns
-     * `true` if the number of corresponding variables is just zero.
+     * @return Boolean indicating whether freeparameter names were set. Also
```
Comment (dweindl) [inline include/amici/model.h]:
```suggestion
     * @return Boolean indicating whether free parameter names were set. Also
```

File: python/sdist/amici/constants.py [hunk 2]
```diff
@@ -23,7 +23,7 @@ class SymbolId(str, enum.Enum):
     SPECIES = "species"
     ALGEBRAIC_STATE = "algebraic_state"
     ALGEBRAIC_EQUATION = "algebraic_equation"
-    PARAMETER = "parameter"
+    FREE_PARAMETER = "parameter"
```
Comment (dweindl) [inline python/sdist/amici/constants.py]:
```suggestion
    FREE_PARAMETER = "free_parameter"
```
